BUGS APLASTADOS 10 tarda mucho en andar
Bug 1:
File "Simulador.py", line 427, in <module>
    main()
  File "Simulador.py", line 413, in main
    lista_equipos = armar_equipos(lista_pilotos, 2)
  File "Simulador.py", line 97, in armar_equipos
    for i in range(len(lista_pilotos) / cantidad_equipos):
TypeError: 'float' object cannot be interpreted as an integer
ARREGLADO :D
BUG 2:
 File "Simulador.py", line 430, in <module>
    main()
  File "Simulador.py", line 417, in main
    asignar_gunplas(lista_equipos)   #asigna un Gunpla a cada Piloto
  File "Simulador.py", line 111, in asignar_gunplas
    gunpla = Gunpla()
  File "C:\Users\ruizh\Documents\FIUBA\Algoritmos y Programación I\TP\TP3\TP3-Gunplas\TP3.py", line 73, in __init__
    self.energia_restante   = self.get_energia()
  File "C:\Users\ruizh\Documents\FIUBA\Algoritmos y Programación I\TP\TP3\TP3-Gunplas\TP3.py", line 120, in get_energia
    energia = self.esqueleto.get_energia()
AttributeError: 'NoneType' object has no attribute 'get_energia'
ARREGLADO :D
BUG 3:
Traceback (most recent call last):
  File "Simulador.py", line 428, in <module>
    main()
  File "Simulador.py", line 416, in main
    lista_esqueletos = generar_esqueletos(10, 200, 200, 200, 4)
  File "Simulador.py", line 126, in generar_esqueletos
    while len(esqueletos) < cantidad:
NameError: name 'esqueletos' is not defined
ARREGLADO :dog:
BUG 4:
  File "Simulador.py", line 428, in <module>
    main()
  File "Simulador.py", line 417, in main
    asignar_esqueletos(lista_esqueletos, lista_equipos)
  File "Simulador.py", line 142, in asignar_esqueletos
    esqueleto_elegido = piloto.elegir_esqueleto()
  File "C:\Users\ruizh\Documents\FIUBA\Algoritmos y Programación I\TP\TP3\TP3-Gunplas\TP3.py", line 357, in elegir_esqueleto
    return random.choice(lista_esqueletos)
  File "C:\Users\ruizh\AppData\Local\Programs\Python\Python36-32\lib\random.py", line 256, in choice
    i = self._randbelow(len(seq))
ARREGLADO :d
BUG 5:
 File "Simulador.py", line 428, in <module>
    main()
  File "Simulador.py", line 417, in main
    asignar_esqueletos(lista_esqueletos, lista_equipos)
  File "Simulador.py", line 142, in asignar_esqueletos
    esqueleto_elegido = piloto.elegir_esqueleto()
TypeError: elegir_esqueleto() missing 1 required positional argument: 'lista_esqueletos'
ARREGLADO :d
BUG 6:
Traceback (most recent call last):
  File "Simulador.py", line 428, in <module>
    main()
  File "Simulador.py", line 417, in main
    asignar_esqueletos(lista_esqueletos, lista_equipos)
  File "Simulador.py", line 143, in asignar_esqueletos
    piloto.get_gunpla()._set.esqueleto(esqueleto_elegido)
AttributeError: 'Gunpla' object has no attribute '_set'
PS C:\Users\ruizh\Documents\FIUBA\Algoritmos y Programación I\TP\TP3\TP3-Gunplas>
ARREGLADO :d
BUG 7:
Traceback (most recent call last):
  File "Simulador.py", line 428, in <module>
    main()
  File "Simulador.py", line 418, in main
    lista_armas = generar_armas(20, 750 , 5 , 90 , 100 , 50 , 50 , 100 , 50)
  File "Simulador.py", line 151, in generar_armas
    while len(armas) < cantidad:
NameError: name 'armas' is not defined
ARREGLADO :+1:
BUG 8:
Traceback (most recent call last):
  File "Simulador.py", line 428, in <module>
    main()
  File "Simulador.py", line 418, in main
    lista_armas = generar_armas(20, 750 , 5 , 90 , 100 , 50 , 50 , 100 , 50)
  File "Simulador.py", line 152, in generar_armas
    arma                = Arma()
  File "C:\Users\ruizh\Documents\FIUBA\Algoritmos y Programación I\TP\TP3\TP3-Gunplas\TP3.py", line 259, in __init__
    self.tipo_municion  = tipo_municion     #"FISICA"|"LASER"|"HADRON"
NameError: name 'tipo_municion' is not defined
ARREGLADO :+1:
BUG 9:
  File "Simulador.py", line 428, in <module>
    main()
  File "Simulador.py", line 419, in main
    lista_partes = generar_partes(50, 200 , 200 , 200, 300, 200, 30 , 4)#los stats de las armas generadas dentro de las partes se cambian desde dentro de la funcion generar_partes
  File "Simulador.py", line 175, in generar_partes
    parte = Parte()
  File "C:\Users\ruizh\Documents\FIUBA\Algoritmos y Programación I\TP\TP3\TP3-Gunplas\TP3.py", line 198, in __init__
    self.peso_base          = peso_base #valor fijo >0
NameError: name 'peso_base' is not defined
ARREGLADO :+1:
BUG 10:
Traceback (most recent call last):
  File "Simulador.py", line 428, in <module>
    main()
  File "Simulador.py", line 419, in main
    lista_partes = generar_partes(50, 200 , 200 , 200, 300, 200, 30 , 4)#los stats de las armas generadas dentro de las partes se cambian desde dentro de la funcion generar_partes
  File "Simulador.py", line 185, in generar_partes
    parte.armas.append(generar_armas(cantidad_armas,200,2,90,0,0,0,50,0)) #se pueden cambiar los valores para que genere armas distintas dentro de las partes
  File "Simulador.py", line 156, in generar_armas
    arma.peso           = random.randint(1,peso)
  File "C:\Users\ruizh\AppData\Local\Programs\Python\Python36-32\lib\random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "C:\Users\ruizh\AppData\Local\Programs\Python\Python36-32\lib\random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)
ARREGLADO :+1: